'use client';
import {useState,useEffect,useCallback} from 'react';
import {KeyRound,Plus,LockKeyhole,RefreshCw,Pencil,Trash2,LoaderCircle,ShieldCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {db} from '@/lib/supabase';
import {type Row,dateLabel,localInput,fromInput} from '@/lib/content';
import {credentialKinds,credentialKey,expiryStatus} from '@/lib/credentials';
import {Pick} from './desk-ui';

export default function CredentialsButton({account}:{account:Row}){
 const [open,setOpen]=useState(false);
 return <><button type="button" className="secondary credential-button" title="টোকেন ও API তথ্য" aria-label={account.name+' — টোকেন ও API তথ্য'} onClick={()=>setOpen(true)}><KeyRound size={17}/><span>টোকেন</span></button>{open&&<CredentialPanel account={account} close={()=>setOpen(false)}/>}</>
}
function CredentialPanel({account,close}:{account:Row;close:()=>void}){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[setup,setSetup]=useState(false),[success,setSuccess]=useState(''),[form,setForm]=useState<Row|true|null>(null),[removing,setRemoving]=useState<Row|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');setSetup(false);try{const {data,error}=await db.rpc('list_social_credentials',{p_destination_id:account.id});if(error){setSetup(error.code==='PGRST202'||error.code==='42883');throw error}setRows(data||[])}catch{setError('টোকেনের তালিকা পাওয়া যায়নি। সেটআপ সম্পন্ন থাকলে আবার চেষ্টা করো।')}finally{setLoading(false)}},[account.id]);
 useEffect(()=>{load()},[load]);
 async function remove(){if(!removing)return;setBusy(true);setError('');try{const {error}=await db.rpc('remove_social_credential',{p_credential_id:removing.id});if(error)throw error;setRemoving(null);setSuccess('সংরক্ষিত তথ্য মুছে ফেলা হয়েছে।');await load()}catch{setError('মুছে ফেলা যায়নি। আবার চেষ্টা করো।')}finally{setBusy(false)}}
 return <Dialog open onOpenChange={o=>{if(!o&&!busy)close()}}><DialogContent className="credential-dialog"><DialogHeader><span className="section-kicker">AUTOMATION CREDENTIALS</span><DialogTitle>টোকেন ও API তথ্য</DialogTitle><DialogDescription>{account.name} · সেভ করা টোকেন আবার দেখানো হবে না।</DialogDescription></DialogHeader><div className="credential-assurance"><ShieldCheck size={20}/><p>গোপন তথ্য এনক্রিপ্ট করে রাখা হবে। ভবিষ্যতের অটোমেশন নিরাপদ সার্ভার থেকে এটি ব্যবহার করতে পারবে।</p></div>
 {setup?<div className="credential-setup"><strong>একবার সেটআপ প্রয়োজন</strong><p>দেওয়া SQL ফাইলটি Supabase SQL Editor-এ চালিয়ে নিচের বাটন চাপো।</p><button className="secondary" onClick={load}><RefreshCw size={16}/>আবার পরীক্ষা করো</button></div>:error&&<div className="error-message" role="alert">{error}<button className="text-button" onClick={load}>আবার চেষ্টা করো</button></div>}
 {success&&<div role="status" className="success-message">{success}</div>}
 {loading?<div className="quiet-empty"><LoaderCircle size={18} className="spin"/>তথ্য লোড হচ্ছে…</div>:!setup&&!error&&<><div className="credential-toolbar"><span>{rows.length}টি তথ্য সংরক্ষিত</span><button className="secondary" onClick={()=>{setSuccess('');setForm(true)}}><Plus size={16}/>তথ্য যোগ করো</button></div>{!rows.length&&<div className="credential-empty"><KeyRound size={27}/><strong>এখনো টোকেন যোগ করা হয়নি</strong><p>Access token, app secret বা অ্যাকাউন্ট ID যোগ করো।</p></div>}{rows.map(row=>{const status=expiryStatus(row.expires_at);return <div className="credential-row" key={row.id}><div className="credential-lock"><LockKeyhole size={18}/></div><div className="credential-meta"><strong>{row.label}</strong><code>{row.credential_key}</code><div className="credential-timing"><span className={'credential-state '+status.className}>{status.label}</span>{row.expires_at&&<span>{dateLabel(row.expires_at,true)}</span>}</div>{row.scopes?.length>0&&<p className="credential-scopes">অনুমতি: {row.scopes.join(', ')}</p>}<small>আপডেট: {dateLabel(row.updated_at,true)}</small></div><div className="row-actions"><button className="icon-button" aria-label={row.label+' আপডেট করো'} onClick={()=>setForm(row)}><Pencil size={16}/></button><button className="icon-button" aria-label={row.label+' মুছে ফেলো'} onClick={()=>setRemoving(row)}><Trash2 size={16}/></button></div></div>})}<p className="credential-footnote">এখানে তথ্য সেভ করা মানেই সোশ্যাল প্ল্যাটফর্মে সংযোগ যাচাই বা অটোমেশন চালু হওয়া নয়।</p></>}
 {form&&<CredentialForm key={typeof form==='object'?form.id:'new'} account={account} row={typeof form==='object'?form:undefined} close={()=>setForm(null)} saved={async()=>{setForm(null);setSuccess('তথ্য নিরাপদে সংরক্ষণ হয়েছে।');await load()}}/>}
 <AlertDialog open={!!removing} onOpenChange={o=>{if(!o&&!busy)setRemoving(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>সংরক্ষিত তথ্য মুছে ফেলবে?</AlertDialogTitle><AlertDialogDescription>{removing?.label} মুছে গেলে ভবিষ্যতের অটোমেশন এটি ব্যবহার করতে পারবে না। সোশ্যাল প্ল্যাটফর্মে টোকেনটি বাতিল হবে না।</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>বাতিল</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void remove()}}>মুছে ফেলো</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </DialogContent></Dialog>
}
function CredentialForm({account,row,close,saved}:{account:Row;row?:Row;close:()=>void;saved:()=>Promise<void>}){
 const [kind,setKind]=useState(row?(credentialKinds[row.credential_key]?row.credential_key:'custom'):'access_token'),[custom,setCustom]=useState(row?.credential_key||''),[label,setLabel]=useState(row?.label||'Access token'),[value,setValue]=useState(''),[expires,setExpires]=useState(localInput(row?.expires_at)),[scopes,setScopes]=useState<string>((row?.scopes||[]).join(', ')),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{let key:string;try{key=credentialKey(kind,custom)}catch(e){setError((e as Error).message);return}
 if(!row&&!value.trim()){setError('তথ্যের মান দাও।');return}
 if(value.length>65536){setError('এই তথ্যটি অনেক বড়।');return}
 const {error}=await db.rpc('save_social_credential',{p_destination_id:account.id,p_credential_key:key,p_label:label.trim(),p_value:value||null,p_expires_at:fromInput(expires),p_scopes:scopes.split(',').map(x=>x.trim()).filter(Boolean)});
 if(error)throw error;setValue('');await saved();
 }catch{setError('সংরক্ষণ করা যায়নি। সংযোগ ও সেটআপ পরীক্ষা করে আবার চেষ্টা করো।')}finally{setBusy(false)}}
 return <Dialog open onOpenChange={o=>{if(!o&&!busy)close()}}><DialogContent className="editor-dialog credential-form"><DialogHeader><DialogTitle>{row?'সংরক্ষিত তথ্য আপডেট':'টোকেন / API তথ্য যোগ করো'}</DialogTitle><DialogDescription>{account.name}</DialogDescription></DialogHeader><form onSubmit={submit}><fieldset disabled={busy} className="form-grid"><label>তথ্যের ধরন<Pick value={kind} label="ধরন" disabled={!!row} options={credentialKinds} onChange={v=>{setKind(v);setLabel(v==='custom'?'':credentialKinds[v])}}/></label><label>নাম<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={100} required/></label>{kind==='custom'&&<label className="full">ইংরেজি পরিচয় — যেমন api_token<input value={custom} onChange={e=>setCustom(e.target.value)} pattern="[a-z][a-z0-9_]{0,63}" maxLength={64} required disabled={!!row}/></label>}<label className="full">{row?'নতুন মান — খালি রাখলে আগেরটি থাকবে':'টোকেন / মান'}<input type="password" value={value} onChange={e=>setValue(e.target.value)} autoComplete="new-password" spellCheck={false} required={!row} maxLength={65536} placeholder={row?'আগের মান গোপন আছে':'এখানে পেস্ট করো'}/></label><label className="full">মেয়াদ শেষ হওয়ার সময় · ঢাকা (ঐচ্ছিক)<input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/></label><label className="full">অনুমতি / scopes — কমা দিয়ে আলাদা করো (ঐচ্ছিক)<input value={scopes} onChange={e=>setScopes(e.target.value)} placeholder="যে অনুমতিগুলো টোকেনকে দেওয়া আছে"/></label></fieldset>{error&&<div className="error-message" role="alert">{error}</div>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={close}>বাতিল</button><button className="primary" disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:<LockKeyhole size={17}/>}নিরাপদে সেভ করো</button></div></form></DialogContent></Dialog>
}

