'use client';
import {useEffect,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {ArrowRight,Layers3,LockKeyhole,LoaderCircle} from 'lucide-react';
import {db} from '@/lib/supabase';
import Workspace from './workspace';
export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{db.auth.getSession().then(({data,error})=>{setSession(data.session);setReady(true);if(error)setError('সেশন পাওয়া যায়নি। আবার লগইন করো।')});const {data}=db.auth.onAuthStateChange((_e,s)=>{setSession(s);setReady(true)});return()=>data.subscription.unsubscribe()},[]);
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const {error}=await db.auth.signInWithPassword({email:String(f.get('email')).trim(),password:String(f.get('password'))});if(error)setError(error.message==='Invalid login credentials'?'ইমেইল অথবা পাসওয়ার্ড মেলেনি। আবার চেষ্টা করো।':error.message)}catch{setError('সংযোগ পাওয়া যাচ্ছে না। আবার চেষ্টা করো।')}finally{setBusy(false)}}
 if(session)return <Workspace key={session.user.id} session={session}/>;
 return <main className="login-page"><section className="login-story"><a href="/" className="brand"><span className="brand-icon"><Layers3 size={23}/></span>content<span className="brand-light">desk</span><span className="brand-dot">.</span></a><div className="login-intro"><span className="eyebrow">YOUR CONTENT WORKSPACE</span><h1>আইডিয়া থেকে পোস্ট।<br/><span>সবকিছুর হিসাব।</span></h1><p>তোমার দুই বিজনেসের কনটেন্ট, প্রকাশের পরিকল্পনা আর ফলাফল—এক জায়গায়।</p><div className="flow-labels"><span>01 &nbsp; তৈরি</span><i/><span>02 &nbsp; প্রকাশ</span><i/><span>03 &nbsp; ফলাফল</span></div></div><div className="login-foot"><span className="tiny-dot"/> তোমার নিজের ওয়ার্কস্পেস</div></section><section className="login-form-side"><div className="login-card"><div className="login-lock"><LockKeyhole size={23}/></div><h2>ফিরে এসো তোমার ডেস্কে</h2><p className="muted">তোমার ইমেইল ও পাসওয়ার্ড দিয়ে লগইন করো।</p><form onSubmit={login}><label>ইমেইল<input name="email" type="email" autoComplete="username" placeholder="you@business.com" required disabled={busy}/></label><label>পাসওয়ার্ড<input name="password" type="password" autoComplete="current-password" placeholder="তোমার পাসওয়ার্ড" required disabled={busy}/></label>{error&&<div role="alert" className="error-message">{error}</div>}<button className="primary login-submit" disabled={busy||!ready}>{busy||!ready?<LoaderCircle className="spin" size={18}/>:<>লগইন <ArrowRight size={18}/></>}</button></form><span className="login-note"><LockKeyhole size={13}/> ব্যক্তিগত কনটেন্ট লাইব্রেরি</span></div></section></main>
}
